version: '3'

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: mysql
    platform: linux/amd64
    container_name: my-mysql-8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
